name: "New Issue"
description: "Use this template to provide your name and designation."
title: "New Issue: [Your Name Here]"
labels: []
assignees: []
body:
  - type: input
    id: name
    attributes:
      label: "Your Name"
      description: "Please enter your full name."
      placeholder: "e.g. Jane Doe"
      required: true

  - type: input
    id: designation
    attributes:
      label: "Your Designation"
      description: "Please provide your designation or role."
      placeholder: "e.g. Software Engineer"
      required: true
