name: Parse Issue Data
on:
  issues:
    types: [opened]

jobs:
  parse:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Body
        uses: imjohnbo/issue-body-parser@v1
        with:
          # By default, this action will parse the issue body from the event payload.
          # If you're using issue forms, it automatically extracts the form fields.
          # You can optionally set a 'prefix' or other parsing options; see the action docs for details.
          prefix: ""

      - name: Print Parsed Output
        run: |
          # The parsed values will be available as step outputs.
          # For Issue Forms, each form field will appear as an output keyed by the field's 'id'.
          # Print all outputs as JSON:
          echo "Parsed Values:"
          echo "${{ toJson(steps.parse.outputs) }}"
