name: Parse Issue Data
on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Issue Fields
        run: |
          BODY=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH")

          # Define the headings you want to parse here
          HEADINGS=("Your Name" "Your Designation")

          OUTPUT="{"
          for H in "${HEADINGS[@]}"; do
            FULL_HEADING="### ${H}"
            VALUE=$(echo "$BODY" | awk -v h="$FULL_HEADING" '$0==h {getline; print}')
            # Convert heading to a JSON-friendly key by replacing spaces with underscores
            KEY=$(echo "$H" | tr ' ' '_')
            OUTPUT+="\"$KEY\": \"$VALUE\","
          done
          # Remove trailing comma and finalize the JSON object
          OUTPUT="${OUTPUT%,}}"

          echo "$OUTPUT"
