name: Handle issue open

on: 
  issues:
    types:
      - opened

jobs:
  process-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.lables.*.name,'test')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
