name: Parse Issue Form
on:
  issues:
    types: [opened]

jobs:
  parse-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Convert Issue Form to JSON
        # Uses the issue-form-json action from GitHub Marketplace
        uses: github-actions-experiments/issue-form-json@v1

      - name: Print Parsed JSON
        run: |
          echo "Issue form as JSON:"
          echo "${{ steps.convert.outputs.json }}"

      - name: Extract Specific Fields
        run: |
          # If your form has fields like "name" and "designation" (defined in the issue form YAML):
          # You can extract them using jq:
          NAME=$(echo "${{ steps.convert.outputs.json }}" | jq -r '.name')
          DESIGNATION=$(echo "${{ steps.convert.outputs.json }}" | jq -r '.designation')

          echo "Name: $NAME"
          echo "Designation: $DESIGNATION"
